In [1]:
#1 Дано: списки a,b=[1,1,1],[3,3,3]
#Создать одномерные массивы A и B из списков а и b.
#Вычислить выражение  −((𝐵−А)∗(𝐵/2))
import numpy as np
a,b=[1,1,1],[3,3,3]
A, B = np.array(a), np.array(b)
res = -((B - A) * (B / 2))
print(res)

[-3. -3. -3.]


In [72]:
#2 Используя как можно меньше операций в исходном массиве 
#"шахматная доска" np.zeros((8,8)), добиться расстановки кодов 
#"шахматных фигур".

'''
Ожидаемый результат:

[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

'''
import numpy as np
x = np.zeros((8,8))
x[0, 0::7], x[7, 0::7] = -4, 4 
x[0, 1::5], x[7, 1::5] = -3, 3
x[0, 2::3], x[7, 2::3] = -2, 2
x[0, 3], x[7, 3] = -6, 6
x[0, 4], x[7, 4] = -5, 5
x[1], x[6] = -1, 1

print(x)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


In [73]:
#3 Средствами NumPy рассчитать произведения четных чисел от 2 до 20 
#на ближайшие к ним бОльшие нечетные числа
import numpy as np
nums = np.arange(2, 21, 2)
nech_nums = nums + 1
prod = nums * nech_nums
print(prod)




[  6  20  42  72 110 156 210 272 342 420]


In [78]:
#4Сгенерировать двумерный массив arr размерности (4, 7), 
#состоящий из случайных действительных чисел, равномерно 
#распределенных в дипазоне от 0 до 20. Нормализовать значения 
#массива так, что после нормализации максимальный элемент масива 
#будет равен 1.0, минимальный 0.0. Значения округлить 
#(с помощью np.round()) до четырех десятичных знаков.
import numpy as np
arr = np.random.uniform(0, 20, (4, 7))
print(arr)
min_val = arr.min()
max_val = arr.max()
norm = np.round((arr - min_val) / (max_val - min_val), 4)
print()
print(norm)

[[11.9462442  14.91073526  8.71296375  2.36118182 10.37765271  1.51238445
  10.63665288]
 [10.99996757 11.85048715  2.16038202 10.53572667  1.50103541 15.10184358
  12.79253404]
 [ 4.25681439 19.97944817  2.05186578  6.66723054 15.20089449 15.33109708
   9.05557236]
 [ 0.74722395 11.1485791   4.43666704 10.54609857 10.28226191 16.45958765
   0.29254694]]

[[0.592  0.7425 0.4277 0.1051 0.5123 0.062  0.5254]
 [0.5439 0.5871 0.0949 0.5203 0.0614 0.7522 0.6349]
 [0.2014 1.     0.0894 0.3238 0.7573 0.7639 0.4451]
 [0.0231 0.5514 0.2105 0.5208 0.5074 0.8212 0.    ]]


In [80]:
#5 Имеется массив my_array

'''
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
'''

#Напишите код, с помощью которого можно извлечь из него 
#центральный фрагмент размером 3 х 3, 
#с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

import numpy as np
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
res = my_array[1:4, 1:4]
print(res)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [81]:
#6 Создайте массив my_sin, состоящий из синусов 
#элементов массива my_array. Посчитайте, чему равна сумма 
#элементов полученного массива. Ответ округлите до трёх цифр после запятой.
import numpy as np

my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
my_sin = np.sin(my_array)
res = round(my_sin.sum(), 3)
print(res)

-0.058


In [84]:
#7 Создать матрицу из 20 случайных целых чисел от 0 до 100. 
#Получить второе сверху значение в матрице. 
#Определить индекс этого значения.
import numpy as np
matr = np.random.randint(0, 100, size=(4, 5))
second = np.sort(matr.flatten())[-2]
ind = np.argwhere(matr == second)
print(matr)
print(second)
print(ind)


[[81 20 29  0 55]
 [51  6 55  1 11]
 [42  2 52 35  2]
 [ 7 64 66 75 18]]
75
[[3 3]]


In [90]:
#8 Задать два двухмерных массива ar1 и ar2 размерности (4, 7), 
#состоящих из случайных целых чисел в пределах от 0 до 10. Построить 
#двухмерный массив размерности (4, 7), каждый элемент которого 
#представляет собой максимум (минимум, среднее) из двух значений, 
#находящихся на аналогичной позиции в массивах ar1, ar2.
import numpy as np
arr1 = np.random.randint(0, 11, size=(4, 7))
arr2 = np.random.randint(0, 11, size=(4, 7))
maximum = np.maximum(arr1, arr2)
minimum = np.minimum(arr1, arr2)
srednee = (arr1 + arr2) / 2

print(arr1)
print()
print(arr2)
print()
print(maximum)
print()
print(minimum)
print()
print(srednee)

[[ 2  3  5  1 10  5  3]
 [ 2  6  5  5  8  2  7]
 [10  3  1  1  0 10  5]
 [ 9  5  2  1  0  1  4]]

[[ 9  7  5  3  8  5  5]
 [ 0  0  6  3  2  0  5]
 [ 4  1  8  3  0  6  9]
 [ 7  6  1  9  4  6 10]]

[[ 9  7  5  3 10  5  5]
 [ 2  6  6  5  8  2  7]
 [10  3  8  3  0 10  9]
 [ 9  6  2  9  4  6 10]]

[[2 3 5 1 8 5 3]
 [0 0 5 3 2 0 5]
 [4 1 1 1 0 6 5]
 [7 5 1 1 0 1 4]]

[[5.5 5.  5.  2.  9.  5.  4. ]
 [1.  3.  5.5 4.  5.  1.  6. ]
 [7.  2.  4.5 2.  0.  8.  7. ]
 [8.  5.5 1.5 5.  2.  3.5 7. ]]


In [91]:
#9 Имеется массив great_array
'''
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
'''
#Чему равна сумма элементов массива great_array, значение которых больше 50?
import numpy as np
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

summ = np.sum(great_array[great_array > 50])
print(summ)


5470.0


In [92]:
#10 Переведите массив great_array в одномерную форму. 
#Какое значение в получившемся массиве имеет элемент с индексом 150?
import numpy as np
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
great_array_flatten = great_array.flatten()
x = great_array_flatten[150]
print(x)





7.0710678118654755


In [95]:
#11 Получить индексы, для которых элементы массивов A и B совпадают.
import numpy as np
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

ind = np.where(A == B)
print(ind)



(array([1, 3, 5, 7], dtype=int64),)


In [96]:
#12 Создайте три массива: массив четных чисел от 2 до 20, 
#массив ближайших к числам первого массива бОльших нечётных чисел, 
#массив векторного произведения первого массива на второй. 
#Соедините все массивы в один двумерный массив, расположив исходные 
#массивы в столбцах.
import numpy as np
A = np.arange(2,21,2)
B = A + 1
C = A * B
res = np.column_stack((A, B, C))
print(res)

[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
